### ISSUE TITLE
Release 0.03 broken

### ISSUE THREAD

**Issue by Smile-Autra** [gusye1234/chat-spot#2]
<img width="253" alt="image" src="https://github.com/gusye1234/chat-spot/assets/96519271/a2d036d6-e18c-4703-ac59-3e0c1f65eb31">

**Comment by gusye1234** [comment]
你的macos版本是? 我在13.5.2是可以正常安装滴

**Comment by Smile-Autra** [comment]
> 你的macos版本是? 我在13.5.2是可以正常安装滴

<img width="280" alt="image" src="https://github.com/gusye1234/chat-spot/assets/96519271/02d4bc55-3eb5-49ce-932e-342c52efaa2d">

**Comment by gusye1234** [comment]
你下载的dmg谁arm64的吗?
